name: MotionSicness
favicon: null
layout_spectrum: 0.039515470853075385
typography_spectrum: 0.4870670004747808
title: Deep in the Dark Jungle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050608'
    - '#ff3334'
    - '#ffffff'
    - '#a6000a'
    - '#979797'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.784735610242933
  rhythmicContrast: 0.9250691034831107
purpose: []
